# Generated by Django 2.1.7 on 2019-03-20 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190321_0338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='judul',
        ),
    ]
