# Generated by Django 2.1.7 on 2019-03-25 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupbarang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='testmerch',
            name='deskripbarang',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testmerch',
            name='grupbarang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandise.Grupbarang'),
        ),
    ]
